export const fullMovieList = [
  {
    "movie_url": "https://www.imdb.com/title/tt0001892/?ref_=sr_t_3",
    "title": "Den sorte drøm",
    "poster": "https://m.media-amazon.com/images/M/MV5BZjg0YjAxZDctMDU5MS00NzZiLTkwMjctODczNjNjNjhhYTRhXkEyXkFqcGdeQXVyMzg1ODEwNQ@@._V1_QL75_UX190_CR0,2,190,281_.jpg",
    "release_year": 1911,
    "length_in_min": 53,
    "imdb_rating": 5.8,
    "rating_count": 265,
    "plot": "Two men of high rank are both wooing the beautiful and famous equestrian acrobat Stella. While Stella ignores the jeweler Hirsch, she accepts Count von Waldberg's offer to follow her home, w... Read allTwo men of high rank are both wooing the beautiful and famous equestrian acrobat Stella. While Stella ignores the jeweler Hirsch, she accepts Count von Waldberg's offer to follow her home, where she falls in his arms. At her party some days later Hirsch turns up uninvited. He say... Read allTwo men of high rank are both wooing the beautiful and famous equestrian acrobat Stella. While Stella ignores the jeweler Hirsch, she accepts Count von Waldberg's offer to follow her home, where she falls in his arms. At her party some days later Hirsch turns up uninvited. He says he wants to give Stella a piece of jewelry, but she repulses his advances. When Waldberg... Read all",
    "directors": "Urban Gad|",
    "writers": "Urban Gad|Gebhard Schätzler-Perasini|",
    "stars": "Asta Nielsen|Valdemar Psilander|Gunnar Helsengreen",
    "genres": "Drama"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0001964/?ref_=sr_t_6",
    "title": "Die Verräterin",
    "poster": "https://m.media-amazon.com/images/M/MV5BNjI2Njc0NTAtMzRlOS00ZDU3LTk5NDMtYWVmZmI0ZGExZDNjXkEyXkFqcGdeQXVyMzg1ODEwNQ@@._V1_QL75_UX190_CR0,60,190,281_.jpg",
    "release_year": 1911,
    "length_in_min": 48,
    "imdb_rating": 5.9,
    "rating_count": 100,
    "plot": "A woman betrays the regiment location in which the officer she is interested in is assigned because he despises her, only to regret it when he is caught and try to free him.A woman betrays the regiment location in which the officer she is interested in is assigned because he despises her, only to regret it when he is caught and try to free him.A woman betrays the regiment location in which the officer she is interested in is assigned because he despises her, only to regret it when he is caught and try to free him.",
    "directors": "Urban Gad",
    "writers": "Erich Zeiske|",
    "stars": "Asta Nielsen|Max Obal|Robert Valberg",
    "genres": "Drama"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0002101/?ref_=sr_t_1",
    "title": "Cleopatra",
    "poster": "https://m.media-amazon.com/images/M/MV5BZTcyMGU4ZmYtYTVmYS00NWFkLWExM2MtYWRlYTlhOWYxNjYwXkEyXkFqcGdeQXVyMzE0MjY5ODA@._V1_QL75_UY281_CR9,0,190,281_.jpg",
    "release_year": 1912,
    "length_in_min": 100,
    "imdb_rating": 5.1,
    "rating_count": 620,
    "plot": "The fabled queen of Egypt's affair with Roman general Marc Antony is ultimately disastrous for both of them.The fabled queen of Egypt's affair with Roman general Marc Antony is ultimately disastrous for both of them.The fabled queen of Egypt's affair with Roman general Marc Antony is ultimately disastrous for both of them.",
    "directors": "Charles L. Gaskill|",
    "writers": "Victorien Sardou|Charles L. Gaskill|",
    "stars": "Helen Gardner|Pearl Sindelar|Miss Fielding",
    "genres": "Drama|History"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0002130/?ref_=sr_t_1",
    "title": "L'Inferno",
    "poster": "https://m.media-amazon.com/images/M/MV5BMzY0NTA4ZTktOTk4ZC00ODg5LTk5OTQtNGJiYzU1MWQ2NTRhXkEyXkFqcGdeQXVyMzg1ODEwNQ@@._V1_QL75_UX190_CR0,12,190,281_.jpg",
    "release_year": 1911,
    "length_in_min": 71,
    "imdb_rating": 7,
    "rating_count": 3500,
    "plot": "Loosely adapted from Dante's Divine Comedy and inspired by the illustrations of Gustav Doré the original silent film has been restored and has a new score by Tangerine Dream.Loosely adapted from Dante's Divine Comedy and inspired by the illustrations of Gustav Doré the original silent film has been restored and has a new score by Tangerine Dream.Loosely adapted from Dante's Divine Comedy and inspired by the illustrations of Gustav Doré the original silent film has been restored and has a new score by Tangerine Dream.",
    "directors": "Francesco Bertolini|Adolfo Padovan|Giuseppe de Liguoro",
    "writers": "Dante Alighieri|",
    "stars": "Salvatore Papa|Arturo Pirovano|Giuseppe de Liguoro",
    "genres": "Adventure|Drama|Fantasy"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0002186/?ref_=sr_t_6",
    "title": "Den flyvende cirkus",
    "poster": "https://m.media-amazon.com/images/M/MV5BZTljZDk2YjUtYzA4ZC00ZjFiLTk2NmYtNTcwZWNiYTY4ZWI4XkEyXkFqcGdeQXVyODg3Mjk3Mjc@._V1_QL75_UY281_CR2,0,190,281_.jpg",
    "release_year": 1912,
    "length_in_min": 46,
    "imdb_rating": 6.4,
    "rating_count": 145,
    "plot": "The Flying Circus was the largest traveling artist band in the country, and among its favorite artists were the rope-dancer, Laurento and the snake tamer, Ula Kiri. The hot blooded gypsy sna... Read allThe Flying Circus was the largest traveling artist band in the country, and among its favorite artists were the rope-dancer, Laurento and the snake tamer, Ula Kiri. The hot blooded gypsy snake tamer is passionately in love with the attractive young man, hut he does not quite retu... Read allThe Flying Circus was the largest traveling artist band in the country, and among its favorite artists were the rope-dancer, Laurento and the snake tamer, Ula Kiri. The hot blooded gypsy snake tamer is passionately in love with the attractive young man, hut he does not quite return her feelings. She is hasty and ill-tempered, and not far from being cruel to those depe... Read all",
    "directors": "Alfred Lind|",
    "writers": "Carl Otto Dumreicher|Alfred Lind|",
    "stars": "Rasmus Ottesen|Emilie Otterdahl|Lili Beck",
    "genres": "Drama"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0002199/?ref_=sr_t_3",
    "title": "From the Manger to the Cross",
    "poster": "https://m.media-amazon.com/images/M/MV5BZTQ3MDdkMWEtYjJmMS00YmE3LTgxMDktOWUwZjczMTdhNGQ1XkEyXkFqcGdeQXVyODg3Mjk3Mjc@._V1_QL75_UX190_CR0,1,190,281_.jpg",
    "release_year": 1912,
    "length_in_min": 60,
    "imdb_rating": 5.8,
    "rating_count": 638,
    "plot": "An account of the life of Jesus Christ according to the New Testament, told as a series of tableaus interspersed with Bible verses.An account of the life of Jesus Christ according to the New Testament, told as a series of tableaus interspersed with Bible verses.An account of the life of Jesus Christ according to the New Testament, told as a series of tableaus interspersed with Bible verses.",
    "directors": "Sidney Olcott",
    "writers": "Gene Gauntier|",
    "stars": "R. Henderson Bland|Percy Dyer|Gene Gauntier",
    "genres": "Biography|Drama"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0002423/?ref_=sr_t_9",
    "title": "Madame DuBarry",
    "poster": "https://m.media-amazon.com/images/M/MV5BODIwYTFjYWMtNjZiOC00ZWM0LTkzMTAtOGVjYzE1Y2VlMmZjXkEyXkFqcGdeQXVyMzg1ODEwNQ@@._V1_QL75_UY281_CR3,0,190,281_.jpg",
    "release_year": 1919,
    "length_in_min": 113,
    "imdb_rating": 6.6,
    "rating_count": 1000,
    "plot": "The story of Madame DuBarry, the mistress of Louis XV of France, and her loves in the time of the French revolution.The story of Madame DuBarry, the mistress of Louis XV of France, and her loves in the time of the French revolution.The story of Madame DuBarry, the mistress of Louis XV of France, and her loves in the time of the French revolution.",
    "directors": "Ernst Lubitsch|",
    "writers": "Norbert Falk|Hanns Kräly|",
    "stars": "Pola Negri|Emil Jannings|Harry Liedtke",
    "genres": "Biography|Drama|Romance"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0002445/?ref_=sr_t_2",
    "title": "Quo Vadis?",
    "poster": "https://m.media-amazon.com/images/M/MV5BOTkyNjk5NzA4Nl5BMl5BanBnXkFtZTgwMDY1NjkwMjE@._V1_QL75_UY281_CR11,0,190,281_.jpg",
    "release_year": 1913,
    "length_in_min": 120,
    "imdb_rating": 6.1,
    "rating_count": 440,
    "plot": "An epic Italian film, \"Quo Vadis\" influenced many of the later movies.An epic Italian film, \"Quo Vadis\" influenced many of the later movies.An epic Italian film, \"Quo Vadis\" influenced many of the later movies.",
    "directors": "Enrico Guazzoni|",
    "writers": "Henryk Sienkiewicz|Enrico Guazzoni|",
    "stars": "Amleto Novelli|Gustavo Serena|Carlo Cattaneo",
    "genres": "Drama|History"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0002452/?ref_=sr_t_2",
    "title": "Independenta Romaniei",
    "poster": "https://m.media-amazon.com/images/M/MV5BOTFlZmRmYzgtZWNlMy00NmQ0LTg0YzktYWFhYzhmZWVkNmVmXkEyXkFqcGdeQXVyMTk3NTc0MTk@._V1_QL75_UY281_CR13,0,190,281_.jpg",
    "release_year": 1912,
    "length_in_min": 120,
    "imdb_rating": 6.4,
    "rating_count": 271,
    "plot": "The movie depicts the Romanian War of Independence (1877-1878).The movie depicts the Romanian War of Independence (1877-1878).The movie depicts the Romanian War of Independence (1877-1878).",
    "directors": "Aristide Demetriade|Grigore Brezeanu|",
    "writers": "Grigore Brezeanu|Aristide Demetriade|Petre Liciu|",
    "stars": "Aristide Demetriade|Constanta Demetriade|Constantin Nottara",
    "genres": "History|War"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0002461/?ref_=sr_t_4",
    "title": "Richard III",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTQ1ODY2NTU4OF5BMl5BanBnXkFtZTgwNTc3NjU4MDE@._V1_QL75_UY281_CR0,0,190,281_.jpg",
    "release_year": 1912,
    "length_in_min": 55,
    "imdb_rating": 5.7,
    "rating_count": 321,
    "plot": "Richard of Gloucester uses manipulation and murder to gain the English throne.Richard of Gloucester uses manipulation and murder to gain the English throne.Richard of Gloucester uses manipulation and murder to gain the English throne.",
    "directors": "André Calmettes|James Keane|",
    "writers": "James Keane|William Shakespeare|",
    "stars": "Robert Gemp|Frederick Warde|Albert Gardner",
    "genres": "Drama"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0002628/?ref_=sr_t_15",
    "title": "Der Andere",
    "poster": "https://m.media-amazon.com/images/M/MV5BNzFlYzNmODEtMDM1Mi00OTdhLWEzYjgtZDJjNzVjMDBlYjNjXkEyXkFqcGdeQXVyNDMzNDQ4ODA@._V1_QL75_UY281_CR11,0,190,281_.jpg",
    "release_year": 1913,
    "length_in_min": 48,
    "imdb_rating": 5.5,
    "rating_count": 114,
    "plot": "A man has an accident while out riding his horse one day. He soon discovers that he now has a split personality, and that his alternate is helping a criminal to rob his house.A man has an accident while out riding his horse one day. He soon discovers that he now has a split personality, and that his alternate is helping a criminal to rob his house.A man has an accident while out riding his horse one day. He soon discovers that he now has a split personality, and that his alternate is helping a criminal to rob his house.",
    "directors": "Max Mack|",
    "writers": "Paul Lindau|Max Mack|Hippolyte Taine|",
    "stars": "Albert Bassermann|Emmerich Hanus|Nelly Ridon",
    "genres": "Drama|Thriller"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0002646/?ref_=sr_t_8",
    "title": "Atlantis",
    "poster": "https://m.media-amazon.com/images/M/MV5BNzk1OWUzOWMtNzExZi00OWY0LWIyZWEtMGViMTEwZjIxMjVmXkEyXkFqcGdeQXVyMTM2MDY0OTYx._V1_QL75_UY281_CR3,0,190,281_.jpg",
    "release_year": 1913,
    "length_in_min": 121,
    "imdb_rating": 6.5,
    "rating_count": 480,
    "plot": "After Dr. Friedrich's wife becomes mentally unstable and his research papers are rejected, he leaves the country to respite.After Dr. Friedrich's wife becomes mentally unstable and his research papers are rejected, he leaves the country to respite.After Dr. Friedrich's wife becomes mentally unstable and his research papers are rejected, he leaves the country to respite.",
    "directors": "August Blom|",
    "writers": "Axel Garde|Gerhart Hauptmann|Karl-Ludwig Schröder|",
    "stars": "Olaf Fønss|Ida Orloff|Ebba Thomsen",
    "genres": "Drama"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0002844/?ref_=sr_t_3",
    "title": "Fantômas - À l'ombre de la guillotine",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTQxNDAxNDk0Ml5BMl5BanBnXkFtZTgwMDQ0ODEwMzE@._V1_QL75_UX190_CR0,1,190,281_.jpg",
    "release_year": 1913,
    "length_in_min": 54,
    "imdb_rating": 6.9,
    "rating_count": 2500,
    "plot": "Inspector Juve is tasked to investigate and capture an infamous criminal Fantomas.Inspector Juve is tasked to investigate and capture an infamous criminal Fantomas.Inspector Juve is tasked to investigate and capture an infamous criminal Fantomas.",
    "directors": "Louis Feuillade|",
    "writers": "Marcel Allain|Louis Feuillade|Pierre Souvestre|",
    "stars": "René Navarre|Edmund Breon|Georges Melchior",
    "genres": "Crime|Drama"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0002885/?ref_=sr_t_17",
    "title": "From Dusk to Dawn",
    "poster": "https://m.media-amazon.com/images/M/MV5BMDhjNDA4OTYtZDc1ZC00NDQ0LTk1MzMtYjU4NmU5OTk4MGY0XkEyXkFqcGdeQXVyMjAzMTU0NDA@._V1_QL75_UX190_CR0,26,190,281_.jpg",
    "release_year": 1913,
    "length_in_min": 90,
    "imdb_rating": 5.9,
    "rating_count": 113,
    "plot": "An employee of an iron works is fired as a dangerous agitator, and after his friend dies in an explosion at the iron works, he runs for governor on a labor ticket.An employee of an iron works is fired as a dangerous agitator, and after his friend dies in an explosion at the iron works, he runs for governor on a labor ticket.An employee of an iron works is fired as a dangerous agitator, and after his friend dies in an explosion at the iron works, he runs for governor on a labor ticket.",
    "directors": "Frank E. Wolfe",
    "writers": "Frank E. Wolfe|",
    "stars": "George Cummings|Clarence Darrow|Ethel Davis",
    "genres": "Drama"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0002898/?ref_=sr_t_14",
    "title": "Germinal",
    "poster": "https://m.media-amazon.com/images/M/MV5BMjUxMjc2ZmEtYWZiOC00YWZiLWExZDgtMWVkMjEwYTg0MmRmXkEyXkFqcGdeQXVyMDUyOTUyNQ@@._V1_QL75_UY281_CR9,0,190,281_.jpg",
    "release_year": 1913,
    "length_in_min": 150,
    "imdb_rating": 6.9,
    "rating_count": 173,
    "plot": "The mechanic Etienne Lantier is a competent workman out of a job, whose tempestuous disposition is more than atoned for by a good heart. With bundle in hand he looks for work from town to to... Read allThe mechanic Etienne Lantier is a competent workman out of a job, whose tempestuous disposition is more than atoned for by a good heart. With bundle in hand he looks for work from town to town and in vain until he comes to the coal mines of Montsou. Luckily for him there is a vac... Read allThe mechanic Etienne Lantier is a competent workman out of a job, whose tempestuous disposition is more than atoned for by a good heart. With bundle in hand he looks for work from town to town and in vain until he comes to the coal mines of Montsou. Luckily for him there is a vacancy because of a workman being absent, and the foreman, Maheu, hires him at the suggestio... Read all",
    "directors": "Albert Capellani|",
    "writers": "Albert Capellani|Émile Zola|",
    "stars": "Mévisto|Jean Jacquinet|Henry Krauss",
    "genres": "Drama"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0003014/?ref_=sr_t_5",
    "title": "Ingeborg Holm",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTQyNDA4OTk1OV5BMl5BanBnXkFtZTgwNTI5NzgwMzE@._V1_QL75_UX190_CR0,2,190,281_.jpg",
    "release_year": 1913,
    "length_in_min": 96,
    "imdb_rating": 7,
    "rating_count": 1400,
    "plot": "Financial struggles separate a single mother from her children.Financial struggles separate a single mother from her children.Financial struggles separate a single mother from her children.",
    "directors": "Victor Sjöström|",
    "writers": "Nils Krok|Victor Sjöström|",
    "stars": "Hilda Borgström|Georg Grönroos|Aron Lindgren",
    "genres": "Drama"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0003037/?ref_=sr_t_6",
    "title": "Juve contre Fantômas",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTFkM2M4MTAtMTE2NC00MjZlLThlZDctMWU3YTIwY2ViMzU4XkEyXkFqcGdeQXVyMDI3OTIzOA@@._V1_QL75_UY281_CR2,0,190,281_.jpg",
    "release_year": 1913,
    "length_in_min": 61,
    "imdb_rating": 6.9,
    "rating_count": 1700,
    "plot": "In Part Two of Louis Feuillade's 5 1/2-hour epic follows Fantômas, the criminal lord of Paris, master of disguise, the creeping assassin in black, as he is pursued by the equally resourceful... Read allIn Part Two of Louis Feuillade's 5 1/2-hour epic follows Fantômas, the criminal lord of Paris, master of disguise, the creeping assassin in black, as he is pursued by the equally resourceful Inspector Juve.In Part Two of Louis Feuillade's 5 1/2-hour epic follows Fantômas, the criminal lord of Paris, master of disguise, the creeping assassin in black, as he is pursued by the equally resourceful Inspector Juve.",
    "directors": "Louis Feuillade|",
    "writers": "Marcel Allain|Louis Feuillade|Pierre Souvestre|",
    "stars": "René Navarre|Edmund Breon|Georges Melchior",
    "genres": "Crime|Drama"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0003102/?ref_=sr_t_25",
    "title": "Ma l'amor mio non muore...",
    "poster": "https://m.media-amazon.com/images/M/MV5BNDM1MDU5OGUtMTFmMS00Mjc5LTljMzUtNjAwNjc2ZWIwYWRiXkEyXkFqcGdeQXVyMDk1ODM3MA@@._V1_QL75_UY281_CR88,0,190,281_.jpg",
    "release_year": 1914,
    "length_in_min": 90,
    "imdb_rating": 6.1,
    "rating_count": 152,
    "plot": "Leslie Swayne, an adventurer, in order to obtain enough money to satisfy the needs of his extravagant life, has been bribed to steal the plans of the fortification from the staff officers of... Read allLeslie Swayne, an adventurer, in order to obtain enough money to satisfy the needs of his extravagant life, has been bribed to steal the plans of the fortification from the staff officers of the Grand Duchy of Wallenstein. This undertaking, which at one time would have seemed dif... Read allLeslie Swayne, an adventurer, in order to obtain enough money to satisfy the needs of his extravagant life, has been bribed to steal the plans of the fortification from the staff officers of the Grand Duchy of Wallenstein. This undertaking, which at one time would have seemed difficult to him, becomes very easy, due to the friendship between himself and Colonel Julius... Read all",
    "directors": "Mario Caserini|",
    "writers": "Emiliano Bonetti|G. Monleone|",
    "stars": "Lyda Borelli|Mario Bonnard|Gian Paolo Rosmino",
    "genres": "Drama"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0003131/?ref_=sr_t_18",
    "title": "Maudite soit la guerre",
    "poster": "https://m.media-amazon.com/images/M/MV5BNTRkM2NlMzEtNDU4OC00NzNkLTg3ZDgtZDZkZDI0MDI3MGIyXkEyXkFqcGdeQXVyNzQ1NDIxMDQ@._V1_QL75_UY281_CR6,0,190,281_.jpg",
    "release_year": 1914,
    "length_in_min": 50,
    "imdb_rating": 6.6,
    "rating_count": 189,
    "plot": "An army pilot is on a visit at the home of another army pilot in the neighboured country. He falls in love with his sister. After the outbreak of a war between the two countries, her brother... Read allAn army pilot is on a visit at the home of another army pilot in the neighboured country. He falls in love with his sister. After the outbreak of a war between the two countries, her brother is killed by her friend in a battle, he is killed by some friends of her brother. She eng... Read allAn army pilot is on a visit at the home of another army pilot in the neighboured country. He falls in love with his sister. After the outbreak of a war between the two countries, her brother is killed by her friend in a battle, he is killed by some friends of her brother. She engages her with her brother's friend who was there, but then she finds out about that battle... Read all",
    "directors": "Alfred Machin",
    "writers": "Alfred Machin|",
    "stars": "Baert|Suzanne Berni|Fernand Crommelynck",
    "genres": "Drama|War"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0003165/?ref_=sr_t_12",
    "title": "Le mort qui tue",
    "poster": "https://m.media-amazon.com/images/M/MV5BMjQwMTEwMjg3Ml5BMl5BanBnXkFtZTgwMTg0NDIwMjE@._V1_QL75_UX190_CR0,7,190,281_.jpg",
    "release_year": 1913,
    "length_in_min": 90,
    "imdb_rating": 6.9,
    "rating_count": 1300,
    "plot": "After a body disappears from inside the prison, a series of crimes take place, all seemingly by the dead man. With Juve presumed dead, Fandor must investigate alone. Will Fantomas finally be... Read allAfter a body disappears from inside the prison, a series of crimes take place, all seemingly by the dead man. With Juve presumed dead, Fandor must investigate alone. Will Fantomas finally be brought to justice?After a body disappears from inside the prison, a series of crimes take place, all seemingly by the dead man. With Juve presumed dead, Fandor must investigate alone. Will Fantomas finally be brought to justice?",
    "directors": "Louis Feuillade|",
    "writers": "Marcel Allain|Louis Feuillade|Pierre Souvestre|",
    "stars": "René Navarre|Edmund Breon|Georges Melchior",
    "genres": "Crime|Drama|Mystery"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0003167/?ref_=sr_t_22",
    "title": "Home, Sweet Home",
    "poster": "https://m.media-amazon.com/images/M/MV5BOTZjNzg2MjgtODJkNy00NWM5LTg2MTAtZGVmZTRiOGEyODJhXkEyXkFqcGdeQXVyMjUxODE0MDY@._V1_QL75_UX190_CR0,3,190,281_.jpg",
    "release_year": 1914,
    "length_in_min": 55,
    "imdb_rating": 5.7,
    "rating_count": 283,
    "plot": "John Howard Payne at his most miserable point in life, writes a song which becomes popular and inspires other people at some point in their lives.John Howard Payne at his most miserable point in life, writes a song which becomes popular and inspires other people at some point in their lives.John Howard Payne at his most miserable point in life, writes a song which becomes popular and inspires other people at some point in their lives.",
    "directors": "D.W. Griffith|",
    "writers": "D.W. Griffith|H.E. Aitken|",
    "stars": "Henry B. Walthall|Josephine Crowell|Lillian Gish",
    "genres": "Drama"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0003330/?ref_=sr_t_16",
    "title": "Richard Wagner",
    "poster": "https://m.media-amazon.com/images/M/MV5BYzAxYmI5ZDItODY5MS00YTM3LWJhZjUtMWU2N2YxMGI1MGZmXkEyXkFqcGdeQXVyMDY4MzkyNw@@._V1_QL75_UY281_CR7,0,190,281_.jpg",
    "release_year": 1913,
    "length_in_min": 110,
    "imdb_rating": 6.2,
    "rating_count": 124,
    "plot": "The story of the great German composer, from his childhood through his great triumphs in orchestral and operatic music.The story of the great German composer, from his childhood through his great triumphs in orchestral and operatic music.The story of the great German composer, from his childhood through his great triumphs in orchestral and operatic music.",
    "directors": "Carl Froelich|William Wauer",
    "writers": "William Wauer|",
    "stars": "Giuseppe Becce|Olga Engl|Manny Ziener",
    "genres": "Biography|Drama|History"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0003419/?ref_=sr_t_1",
    "title": "Der Student von Prag",
    "poster": "https://m.media-amazon.com/images/M/MV5BMzA2N2M2ZGItODQ3Ni00Yjg0LTk4NjMtZmI2NTBkNzg3MmQzXkEyXkFqcGdeQXVyMzg1ODEwNQ@@._V1_QL75_UX190_CR0,6,190,281_.jpg",
    "release_year": 1913,
    "length_in_min": 85,
    "imdb_rating": 6.4,
    "rating_count": 2400,
    "plot": "Balduin, a student of Prague, leaves his roystering companions in the beer garden, when he finds he has reached the end of his resources. He is scarcely seated in a quiet corner when a hideo... Read allBalduin, a student of Prague, leaves his roystering companions in the beer garden, when he finds he has reached the end of his resources. He is scarcely seated in a quiet corner when a hideous, shriveled-up old man taps him upon the shoulder and whispers vaguely of a big inherita... Read allBalduin, a student of Prague, leaves his roystering companions in the beer garden, when he finds he has reached the end of his resources. He is scarcely seated in a quiet corner when a hideous, shriveled-up old man taps him upon the shoulder and whispers vaguely of a big inheritance for Prague's finest swordsman and wildest student if he will enter into a certain agre... Read all",
    "directors": "Hanns Heinz Ewers|Stellan Rye|",
    "writers": "Hanns Heinz Ewers|Alfred de Musset|",
    "stars": "Paul Wegener|Grete Berger|Lyda Salmonova",
    "genres": "Drama|Fantasy|Horror"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0003471/?ref_=sr_t_4",
    "title": "Traffic in Souls",
    "poster": "https://m.media-amazon.com/images/M/MV5BYzk0YWQzMGYtYTM5MC00NjM2LWE5YzYtMjgyNDVhZDg1N2YzXkEyXkFqcGdeQXVyMzE0MjY5ODA@._V1_QL75_UY281_CR1,0,190,281_.jpg",
    "release_year": 1913,
    "length_in_min": 88,
    "imdb_rating": 6,
    "rating_count": 731,
    "plot": "With aid from her police-officer sweetheart, a woman endeavors to uncover the prostitution ring that has kidnapped her sister and the philanthropist who secretly runs it.With aid from her police-officer sweetheart, a woman endeavors to uncover the prostitution ring that has kidnapped her sister and the philanthropist who secretly runs it.With aid from her police-officer sweetheart, a woman endeavors to uncover the prostitution ring that has kidnapped her sister and the philanthropist who secretly runs it.",
    "directors": "George Loane Tucker|",
    "writers": "Walter MacNamara|George Loane Tucker|",
    "stars": "Jane Gail|Ethel Grandin|William H. Turner",
    "genres": "Crime|Drama"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0003489/?ref_=sr_t_9",
    "title": "Gli ultimi giorni di Pompei",
    "poster": "https://m.media-amazon.com/images/M/MV5BOTMzMzUzNjM4NV5BMl5BanBnXkFtZTgwODc4NjU4MDE@._V1_QL75_UX190_CR0,4,190,281_.jpg",
    "release_year": 1913,
    "length_in_min": 88,
    "imdb_rating": 6.1,
    "rating_count": 621,
    "plot": "Two love triangles intersect in ancient Pompei.Two love triangles intersect in ancient Pompei.Two love triangles intersect in ancient Pompei.",
    "directors": "Mario Caserini|Eleuterio Rodolfi|",
    "writers": "Edward George Bulwer-Lytton|Mario Caserini|",
    "stars": "Fernanda Negri Pouget|Eugenia Tettoni Fior|Ubaldo Stefani",
    "genres": "Adventure|Drama"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0003637/?ref_=sr_t_13",
    "title": "Assunta Spina",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTUyNTkxOTA5Ml5BMl5BanBnXkFtZTcwMDA0MDIyMQ@@._V1_QL75_UX190_CR0,34,190,281_.jpg",
    "release_year": 1915,
    "length_in_min": 72,
    "imdb_rating": 6.2,
    "rating_count": 492,
    "plot": "Assunta Spina is a tragedy set in Naples at the beginning of the twentieth century. Assunta and Michele are in love but others come between them and there is much jealousy. They fight and Mi... Read allAssunta Spina is a tragedy set in Naples at the beginning of the twentieth century. Assunta and Michele are in love but others come between them and there is much jealousy. They fight and Michele is sent to prison for two years for assault. Nevertheless, because Assunta still lov... Read allAssunta Spina is a tragedy set in Naples at the beginning of the twentieth century. Assunta and Michele are in love but others come between them and there is much jealousy. They fight and Michele is sent to prison for two years for assault. Nevertheless, because Assunta still loves Michele she is vulnerable when Federigo offers to help Michele but only if Assunta beco... Read all",
    "directors": "Francesca Bertini|Gustavo Serena|",
    "writers": "Salvatore Di Giacomo|Francesca Bertini|Gustavo Serena|",
    "stars": "Francesca Bertini|Gustavo Serena|Carlo Benetti",
    "genres": "Drama"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0003643/?ref_=sr_t_10",
    "title": "The Avenging Conscience: or 'Thou Shalt Not Kill'",
    "poster": "https://m.media-amazon.com/images/M/MV5BNDdhMjhhODAtZjAyZS00NGE3LWFjMzUtYmU3ZThkNDExYmU3XkEyXkFqcGdeQXVyMjUxODE0MDY@._V1_QL75_UY281_CR2,0,190,281_.jpg",
    "release_year": 1914,
    "length_in_min": 78,
    "imdb_rating": 6.4,
    "rating_count": 1400,
    "plot": "Prevented from dating his sweetheart by his uncle, a young man turns his thoughts to murder.Prevented from dating his sweetheart by his uncle, a young man turns his thoughts to murder.Prevented from dating his sweetheart by his uncle, a young man turns his thoughts to murder.",
    "directors": "D.W. Griffith|",
    "writers": "Edgar Allan Poe|D.W. Griffith|",
    "stars": "Henry B. Walthall|Spottiswoode Aitken|Blanche Sweet",
    "genres": "Crime|Drama|Horror"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0003657/?ref_=sr_t_24",
    "title": "The Bargain",
    "poster": "https://m.media-amazon.com/images/M/MV5BNjc4NjU0ZDAtMzBiZi00MTU2LTk2MGYtZjcwMDExNmM3MTI3XkEyXkFqcGdeQXVyNjA5MTAzODY@._V1_QL75_UX190_CR0,5,190,281_.jpg",
    "release_year": 1914,
    "length_in_min": 70,
    "imdb_rating": 6.5,
    "rating_count": 252,
    "plot": "The bandit Jim Stokes, wanting to go straight and settle down with his new bride, strikes a bargain with the sheriff for his freedom.The bandit Jim Stokes, wanting to go straight and settle down with his new bride, strikes a bargain with the sheriff for his freedom.The bandit Jim Stokes, wanting to go straight and settle down with his new bride, strikes a bargain with the sheriff for his freedom.",
    "directors": "Reginald Barker|",
    "writers": "William H. Clifford|Thomas H. Ince|Richard V. Spencer|",
    "stars": "William S. Hart|J. Frank Burke|Clara Williams",
    "genres": "Western"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0003665/?ref_=sr_t_23",
    "title": "The Battle of the Sexes",
    "poster": "https://m.media-amazon.com/images/M/MV5BNjIzOTc0ZDItNWM4ZC00NzU2LTkyNGMtYzIwNzU5MmIyNDEwXkEyXkFqcGdeQXVyMDUyOTUyNQ@@._V1_QL75_UY281_CR108,0,190,281_.jpg",
    "release_year": 1914,
    "length_in_min": 50,
    "imdb_rating": 6.2,
    "rating_count": 102,
    "plot": "Frank Andrews is a successful businessman. He has always found pride and joy in the company of his wife, son and daughter. He suddenly finds himself enthralled by the advances of a gay young... Read allFrank Andrews is a successful businessman. He has always found pride and joy in the company of his wife, son and daughter. He suddenly finds himself enthralled by the advances of a gay young woman siren, who lives in the same apartment house as he does. So marked an influence doe... Read allFrank Andrews is a successful businessman. He has always found pride and joy in the company of his wife, son and daughter. He suddenly finds himself enthralled by the advances of a gay young woman siren, who lives in the same apartment house as he does. So marked an influence does she have over him as time progresses that at last he quite forgets his home ties, neglec... Read all",
    "directors": "D.W. Griffith",
    "writers": "Daniel Carson Goodman|",
    "stars": "Donald Crisp|Lillian Gish|Robert Harron",
    "genres": "Drama"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0003740/?ref_=sr_t_1",
    "title": "Cabiria",
    "poster": "https://m.media-amazon.com/images/M/MV5BZGYwZWU2MzMtZGU2My00NWQ1LTlkNDYtYmJjMTAwNWMxYzljXkEyXkFqcGdeQXVyNjg2NjExMzY@._V1_QL75_UY281_CR6,0,190,281_.jpg",
    "release_year": 1914,
    "length_in_min": 148,
    "imdb_rating": 7.1,
    "rating_count": 4000,
    "plot": "Cabiria is a Roman child when her home is destroyed by a volcano. Sold in Carthage to be sacrificed in a temple, she is saved by Fulvio, a Roman spy. But danger lurks, and hatred between Rom... Read allCabiria is a Roman child when her home is destroyed by a volcano. Sold in Carthage to be sacrificed in a temple, she is saved by Fulvio, a Roman spy. But danger lurks, and hatred between Rome and Carthage can only lead to war.Cabiria is a Roman child when her home is destroyed by a volcano. Sold in Carthage to be sacrificed in a temple, she is saved by Fulvio, a Roman spy. But danger lurks, and hatred between Rome and Carthage can only lead to war.",
    "directors": "Giovanni Pastrone|",
    "writers": "Gabriele D'Annunzio|Titus Livius|Giovanni Pastrone|",
    "stars": "Italia Almirante-Manzini|Lidia Quaranta|Bartolomeo Pagano",
    "genres": "Adventure|Drama|History"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0003772/?ref_=sr_t_21",
    "title": "Cinderella",
    "poster": "https://m.media-amazon.com/images/M/MV5BNDRhMGQ1NWMtNmZkNS00MGYxLTg0ZWUtMGRlYmZiMzQ3YTc1XkEyXkFqcGdeQXVyNDY1NzU5NjY@._V1_QL75_UY281_CR1,0,190,281_.jpg",
    "release_year": 1914,
    "length_in_min": 52,
    "imdb_rating": 6,
    "rating_count": 1100,
    "plot": "Though mistreated by her cruel stepmother and stepsisters, Cinderella is able to attend the royal ball through the help of a fairy godmother.Though mistreated by her cruel stepmother and stepsisters, Cinderella is able to attend the royal ball through the help of a fairy godmother.Though mistreated by her cruel stepmother and stepsisters, Cinderella is able to attend the royal ball through the help of a fairy godmother.",
    "directors": "James Kirkwood",
    "writers": "Charles Perrault|",
    "stars": "Mary Pickford|Owen Moore|Isabel Vernon",
    "genres": "Fantasy|Drama"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0003883/?ref_=sr_t_7",
    "title": "L'enfant de Paris",
    "poster": "https://m.media-amazon.com/images/M/MV5BZGE0YWVkYjEtNGM3MC00NDdhLTg5MjYtY2E1YjJiNDdiZThmXkEyXkFqcGdeQXVyMzg1ODEwNQ@@._V1_QL75_UY281_CR9,0,190,281_.jpg",
    "release_year": 1913,
    "length_in_min": 124,
    "imdb_rating": 7.2,
    "rating_count": 450,
    "plot": "The young daughter of an army captain missing in action runs away from school and is kidnapped by Parisian lowlifes. When the kidnapper flees to Nice with the child, the kind-hearted employe... Read allThe young daughter of an army captain missing in action runs away from school and is kidnapped by Parisian lowlifes. When the kidnapper flees to Nice with the child, the kind-hearted employee of one of his accomplices sets off in pursuit.The young daughter of an army captain missing in action runs away from school and is kidnapped by Parisian lowlifes. When the kidnapper flees to Nice with the child, the kind-hearted employee of one of his accomplices sets off in pursuit.",
    "directors": "Léonce Perret",
    "writers": "Léonce Perret|",
    "stars": "Léonce Perret|Louis Leubas|Maurice Lagrenée",
    "genres": "Crime|Drama"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0003884/?ref_=sr_t_32",
    "title": "Engelein",
    "poster": "https://m.media-amazon.com/images/M/MV5BODcyN2IxMTItZDc5YS00ODE3LTkyZTMtMzJiNGViYTY4MjAzXkEyXkFqcGdeQXVyMzg1ODEwNQ@@._V1_QL75_UX190_CR0,56,190,281_.jpg",
    "release_year": 1914,
    "length_in_min": 49,
    "imdb_rating": 6.4,
    "rating_count": 116,
    "plot": "To inherit, 18-year-old Jesta must pretend to only age 12 when her American uncle arrives.To inherit, 18-year-old Jesta must pretend to only age 12 when her American uncle arrives.To inherit, 18-year-old Jesta must pretend to only age 12 when her American uncle arrives.",
    "directors": "Urban Gad",
    "writers": "Urban Gad|",
    "stars": "Asta Nielsen|Alfred Kuehne|Max Landa",
    "genres": "Comedy"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0003897/?ref_=sr_t_11",
    "title": "The Exploits of Elaine",
    "poster": "https://m.media-amazon.com/images/M/MV5BYjNkMWNmY2YtMTI5Ni00YzkyLWIyMmEtMTE3NjVjOWNmZjZiXkEyXkFqcGdeQXVyMDUyOTUyNQ@@._V1_QL75_UX190_CR0,2,190,281_.jpg",
    "release_year": 1914,
    "length_in_min": 220,
    "imdb_rating": 6.1,
    "rating_count": 101,
    "plot": "With the help of a private detective, Elaine tries to catch the masked criminal mastermind The Clutching Hand, who has murdered her father.With the help of a private detective, Elaine tries to catch the masked criminal mastermind The Clutching Hand, who has murdered her father.With the help of a private detective, Elaine tries to catch the masked criminal mastermind The Clutching Hand, who has murdered her father.",
    "directors": "Louis J. Gasnier|George B. Seitz|Leopold Wharton|",
    "writers": "Charles W. Goddard|Arthur B. Reeve|George B. Seitz|",
    "stars": "Pearl White|Arnold Daly|Creighton Hale",
    "genres": "Action"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0003930/?ref_=sr_t_28",
    "title": "Fantômas contre Fantômas",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTA3MTk5MjI1ODBeQTJeQWpwZ15BbWU3MDc1MzAzMzQ@._V1_QL75_UY281_CR1,0,190,281_.jpg",
    "release_year": 1914,
    "length_in_min": 59,
    "imdb_rating": 6.8,
    "rating_count": 1400,
    "plot": "The press and the public opinion suggest that Inspector Juve may in fact be Fantômas. As Juve is jailed, the actual Fantômas schemes to keep him behind bars forever.The press and the public opinion suggest that Inspector Juve may in fact be Fantômas. As Juve is jailed, the actual Fantômas schemes to keep him behind bars forever.The press and the public opinion suggest that Inspector Juve may in fact be Fantômas. As Juve is jailed, the actual Fantômas schemes to keep him behind bars forever.",
    "directors": "Louis Feuillade|",
    "writers": "Marcel Allain|Louis Feuillade|Pierre Souvestre|",
    "stars": "René Navarre|Georges Melchior|Laurent Morléas",
    "genres": "Crime|Drama"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0003952/?ref_=sr_t_30",
    "title": "Le faux magistrat",
    "poster": "https://m.media-amazon.com/images/M/MV5BYTJmNGUxOTktNzg5ZC00ZmM3LWFlYzgtMzMzMTM2NGFlYmM1XkEyXkFqcGdeQXVyODQ0OTczOQ@@._V1_QL75_UX190_CR0,12,190,281_.jpg",
    "release_year": 1914,
    "length_in_min": 70,
    "imdb_rating": 6.7,
    "rating_count": 1200,
    "plot": "Having committed murder in Belgium, Fantomas is sentenced to life imprisonment. Two crimes committed in France suggest to inspector Juve that the Fantomas gang is still at work. He conceives... Read allHaving committed murder in Belgium, Fantomas is sentenced to life imprisonment. Two crimes committed in France suggest to inspector Juve that the Fantomas gang is still at work. He conceives the idea that if Fantomas is set free it will be possible to follow him and capture him a... Read allHaving committed murder in Belgium, Fantomas is sentenced to life imprisonment. Two crimes committed in France suggest to inspector Juve that the Fantomas gang is still at work. He conceives the idea that if Fantomas is set free it will be possible to follow him and capture him and the remaining members of the gang. The villain escapes from prison and makes his way to... Read all",
    "directors": "Louis Feuillade|",
    "writers": "Marcel Allain|Louis Feuillade|Pierre Souvestre|",
    "stars": "René Navarre|Edmund Breon|Georges Melchior",
    "genres": "Crime|Drama"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0003973/?ref_=sr_t_16",
    "title": "A Florida Enchantment",
    "poster": "https://m.media-amazon.com/images/M/MV5BNjE5MTA5NDItNmVhYi00NDljLTg4MjgtMjRhMzVlZmUxYWRlXkEyXkFqcGdeQXVyMDU4MTQ0Ng@@._V1_QL75_UX190_CR0,14,190,281_.jpg",
    "release_year": 1914,
    "length_in_min": 63,
    "imdb_rating": 5.8,
    "rating_count": 300,
    "plot": "A young woman discovers a seed that can make women act like men and men act like women. She decides to take one, then slips one to her maid and another to her fiancé. The fun begins.A young woman discovers a seed that can make women act like men and men act like women. She decides to take one, then slips one to her maid and another to her fiancé. The fun begins.A young woman discovers a seed that can make women act like men and men act like women. She decides to take one, then slips one to her maid and another to her fiancé. The fun begins.",
    "directors": "Sidney Drew|",
    "writers": "Marguerite Bertsch|Archibald Clavering Gunter|Eugene Mullin|",
    "stars": "Sidney Drew|Edith Storey|Charles Kent",
    "genres": "Comedy"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0004026/?ref_=sr_t_5",
    "title": "Der Golem",
    "poster": "https://m.media-amazon.com/images/M/MV5BOTIyN2U4Y2UtZjUzNy00M2Q4LWI2ZGQtOTgwNGE1YTQwZDg5XkEyXkFqcGdeQXVyNzk3ODM4NQ@@._V1_QL75_UY281_CR7,0,190,281_.jpg",
    "release_year": 1914,
    "length_in_min": 60,
    "imdb_rating": 6.7,
    "rating_count": 1200,
    "plot": "An antiques dealer finds a golem, a clay statue that had been brought to life four centuries earlier by a Kabbalist rabbi to protect his people from persecution. The dealer resurrects the go... Read allAn antiques dealer finds a golem, a clay statue that had been brought to life four centuries earlier by a Kabbalist rabbi to protect his people from persecution. The dealer resurrects the golem as a servant but it goes on a rampage.An antiques dealer finds a golem, a clay statue that had been brought to life four centuries earlier by a Kabbalist rabbi to protect his people from persecution. The dealer resurrects the golem as a servant but it goes on a rampage.",
    "directors": "Paul Wegener|Henrik Galeen|",
    "writers": "Paul Wegener|Henrik Galeen|",
    "stars": "Paul Wegener|Henrik Galeen|Lyda Salmonova",
    "genres": "Horror"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0004052/?ref_=sr_t_31",
    "title": "The Hazards of Helen",
    "poster": "https://m.media-amazon.com/images/M/MV5BOTM1OGMxM2EtODQ2MS00N2RhLWJkMWMtNDQ1ZjYzMGYwMmMxXkEyXkFqcGdeQXVyNzI5NjM3NDQ@._V1_QL75_UY281_CR94,0,190,281_.jpg",
    "release_year": 1914,
    "length_in_min": 1428,
    "imdb_rating": 6.8,
    "rating_count": 122,
    "plot": "Helen, informed of the danger which menaces an excursion train because another engine on the same track is running wild, mounts a motorcycle and speeds down the track to warn the passengers ... Read allHelen, informed of the danger which menaces an excursion train because another engine on the same track is running wild, mounts a motorcycle and speeds down the track to warn the passengers of their imminent peril.Helen, informed of the danger which menaces an excursion train because another engine on the same track is running wild, mounts a motorcycle and speeds down the track to warn the passengers of their imminent peril.",
    "directors": "J. Gunnis Davis|J.P. McGowan|Robert G. Vignola|",
    "writers": "Frank Howard Clark|John Russell Corvell|Scott Darling|",
    "stars": "Helen Holmes|Helen Gibson|J.P. McGowan",
    "genres": "Action"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0004066/?ref_=sr_t_15",
    "title": "Det hemmelighedsfulde X",
    "poster": "https://m.media-amazon.com/images/M/MV5BZjMxZjMyNzgtY2MxMS00Y2FkLWI3MTEtYmI2YzY4ZGM3NWE0XkEyXkFqcGdeQXVyNDEzMTI3MTU@._V1_QL75_UX190_CR0,2,190,281_.jpg",
    "release_year": 1914,
    "length_in_min": 84,
    "imdb_rating": 6.8,
    "rating_count": 686,
    "plot": "On the brink of war, Lt. van Hauen is summoned to take command of the cruiser, but due to unforeseen events, he is wrongfully convicted as a traitor.On the brink of war, Lt. van Hauen is summoned to take command of the cruiser, but due to unforeseen events, he is wrongfully convicted as a traitor.On the brink of war, Lt. van Hauen is summoned to take command of the cruiser, but due to unforeseen events, he is wrongfully convicted as a traitor.",
    "directors": "Benjamin Christensen|",
    "writers": "Benjamin Christensen|Laurids Skands|",
    "stars": "Benjamin Christensen|Karen Caspersen|Otto Reinwald",
    "genres": "Drama|Mystery"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0004099/?ref_=sr_t_13",
    "title": "His Majesty, the Scarecrow of Oz",
    "poster": "https://m.media-amazon.com/images/M/MV5BZWZmZTZhMTQtZDhjZS00MTQyLThjMDQtYWYzN2NkYTEyMTJlXkEyXkFqcGdeQXVyMzE0MjY5ODA@._V1_QL75_UY281_CR11,0,190,281_.jpg",
    "release_year": 1914,
    "length_in_min": 59,
    "imdb_rating": 5.4,
    "rating_count": 522,
    "plot": "The wicked king wants his daughter, Princess Gloria, to marry a horrid courtier though she loves the gardener's boy Pon. After encountering Dorothy, Pon and her team up to defeat the evil wi... Read allThe wicked king wants his daughter, Princess Gloria, to marry a horrid courtier though she loves the gardener's boy Pon. After encountering Dorothy, Pon and her team up to defeat the evil witch Mombi and to rescue the princess.The wicked king wants his daughter, Princess Gloria, to marry a horrid courtier though she loves the gardener's boy Pon. After encountering Dorothy, Pon and her team up to defeat the evil witch Mombi and to rescue the princess.",
    "directors": "J. Farrell MacDonald",
    "writers": "L. Frank Baum|",
    "stars": "Violet MacMillan|Frank Moore|Pierre Couderc",
    "genres": "Family|Fantasy|Adventure"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0004121/?ref_=sr_t_19",
    "title": "Der Hund von Baskerville",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTgzMDQxNzgzMF5BMl5BanBnXkFtZTgwNjc4NzYwMjE@._V1_QL75_UY281_CR0,0,190,281_.jpg",
    "release_year": 1914,
    "length_in_min": 65,
    "imdb_rating": 5.6,
    "rating_count": 147,
    "plot": "In this early version the classic \"Hound of the Baskervilles\" mystery is not faithfully adapted, Watson's character is absent and there are two Holmes. Holmes' foe is called Stapleton and he... Read allIn this early version the classic \"Hound of the Baskervilles\" mystery is not faithfully adapted, Watson's character is absent and there are two Holmes. Holmes' foe is called Stapleton and he menaces Holmes' client Lord Henry and his fiancée, Laura Lyons, masquerading himself as H... Read allIn this early version the classic \"Hound of the Baskervilles\" mystery is not faithfully adapted, Watson's character is absent and there are two Holmes. Holmes' foe is called Stapleton and he menaces Holmes' client Lord Henry and his fiancée, Laura Lyons, masquerading himself as Holmes. Hidden passages, hand bombs and mechanical devices abound, reminding more of a seri... Read all",
    "directors": "Rudolf Meinert|",
    "writers": "Arthur Conan Doyle|Richard Oswald|Julius Philipp|",
    "stars": "Alwin Neuß|Friedrich Kühne|Hanni Weisse",
    "genres": "Crime|Mystery|Horror"
  },
];