export const initialMovieList = [
  {
    "movie_url": "https://www.imdb.com/title/tt0001892/?ref_=sr_t_3",
    title: "Den sorte drøm",
    "poster": "https://m.media-amazon.com/images/M/MV5BZjg0YjAxZDctMDU5MS00NzZiLTkwMjctODczNjNjNjhhYTRhXkEyXkFqcGdeQXVyMzg1ODEwNQ@@._V1_QL75_UX190_CR0,2,190,281_.jpg",
    "release_year": 1911,
    "length_in_min": 53,
    "imdb_rating": 5.8,
    "rating_count": 265,
    "plot": "Two men of high rank are both wooing the beautiful and famous equestrian acrobat Stella. While Stella ignores the jeweler Hirsch, she accepts Count von Waldberg's offer to follow her home, where she falls in his arms. At her party some days later Hirsch turns up uninvited. He says he wants to give Stella a piece of jewelry, but she repulses his advances. When Waldberg...",
    "directors": "Urban Gad",
    "writers": "Urban Gad|Gebhard Schützler-Perasini",
    "stars": "Asta Nielsen|Valdemar Psilander|Gunnar Helsengreen",
    "genres": "Drama"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0001964/?ref_=sr_t_6",
    "title": "Die Verräterin",
    "poster": "https://m.media-amazon.com/images/M/MV5BNjI2Njc0NTAtMzRlOS00ZDU3LTk5NDMtYWVmZmI0ZGExZDNjXkEyXkFqcGdeQXVyMzg1ODEwNQ@@._V1_QL75_UX190_CR0,60,190,281_.jpg",
    "release_year": 1911,
    "length_in_min": 48,
    "imdb_rating": 5.9,
    "rating_count": 100,
    "plot": "A woman betrays the regiment location in which the officer she is interested in is assigned because he despises her, only to regret it when he is caught and tries to free him.",
    "directors": "Urban Gad",
    "writers": "Erich Zeiske",
    "stars": "Asta Nielsen|Max Obal|Robert Valberg",
    "genres": "Drama"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0002101/?ref_=sr_t_1",
    "title": "Cleopatra",
    poster: "https://m.media-amazon.com/images/M/MV5BZTcyMGU4ZmYtYTVmYS00NWFkLWExM2MtYWRlYTlhOWYxNjYwXkEyXkFqcGdeQXVyMzE0MjY5ODA@._V1_QL75_UY281_CR9,0,190,281_.jpg",
    "release_year": 1912,
    "length_in_min": 100,
    "imdb_rating": 5.1,
    "rating_count": 620,
    "plot": "The fabled queen of Egypt's affair with Roman general Marc Antony is ultimately disastrous for both of them.",
    "directors": "Charles L. Gaskill",
    "writers": "Victorien Sardou|Charles L. Gaskill",
    "stars": "Helen Gardner|Pearl Sindelar|Miss Fielding",
    "genres": "Drama|History"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0001892/?ref_=sr_t_3",
    "title": "Den sorte drøm",
    poster: "https://m.media-amazon.com/images/M/MV5BZjg0YjAxZDctMDU5MS00NzZiLTkwMjctODczNjNjNjhhYTRhXkEyXkFqcGdeQXVyMzg1ODEwNQ@@._V1_QL75_UX190_CR0,2,190,281_.jpg",
    "release_year": 1911,
    "length_in_min": 53,
    "imdb_rating": 5.8,
    "rating_count": 265,
    "plot": "Two men of high rank are both wooing the beautiful and famous equestrian acrobat Stella. While Stella ignores the jeweler Hirsch, she accepts Count von Waldberg's offer to follow her home, where she falls in his arms. At her party some days later Hirsch turns up uninvited. He says he wants to give Stella a piece of jewelry, but she repulses his advances. When Waldberg...",
    "directors": "Urban Gad",
    "writers": "Urban Gad|Gebhard Schützler-Perasini",
    "stars": "Asta Nielsen|Valdemar Psilander|Gunnar Helsengreen",
    "genres": "Drama"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0001964/?ref_=sr_t_6",
    "title": "Die Verräterin",
    poster: "https://m.media-amazon.com/images/M/MV5BNjI2Njc0NTAtMzRlOS00ZDU3LTk5NDMtYWVmZmI0ZGExZDNjXkEyXkFqcGdeQXVyMzg1ODEwNQ@@._V1_QL75_UX190_CR0,60,190,281_.jpg",
    "release_year": 1911,
    "length_in_min": 48,
    "imdb_rating": 5.9,
    "rating_count": 100,
    "plot": "A woman betrays the regiment location in which the officer she is interested in is assigned because he despises her, only to regret it when he is caught and tries to free him.",
    "directors": "Urban Gad",
    "writers": "Erich Zeiske",
    "stars": "Asta Nielsen|Max Obal|Robert Valberg",
    "genres": "Drama"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0002101/?ref_=sr_t_1",
    "title": "Cleopatra",
    poster: "https://m.media-amazon.com/images/M/MV5BZTcyMGU4ZmYtYTVmYS00NWFkLWExM2MtYWRlYTlhOWYxNjYwXkEyXkFqcGdeQXVyMzE0MjY5ODA@._V1_QL75_UY281_CR9,0,190,281_.jpg",
    "release_year": 1912,
    "length_in_min": 100,
    "imdb_rating": 5.1,
    "rating_count": 620,
    "plot": "The fabled queen of Egypt's affair with Roman general Marc Antony is ultimately disastrous for both of them.",
    "directors": "Charles L. Gaskill",
    "writers": "Victorien Sardou|Charles L. Gaskill",
    "stars": "Helen Gardner|Pearl Sindelar|Miss Fielding",
    "genres": "Drama|History"
  }
];