export const initialMovieList = [
  {
    "movie_url": "https://www.imdb.com/title/tt0007361/?ref_=sr_t_3",
    "title": "Snow White",
    "poster": "https://m.media-amazon.com/images/M/MV5BMjk0NTJjY2UtMWNjNi00MGM1LWEzNGEtMjI2OWI1NzQwOWY2L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMjUxODE0MDY@._V1_QL75_UX190_CR0,10,190,281_.jpg",
    "release_year": 1916,
    "length_in_min": 63,
    "imdb_rating": 6.3,
    "rating_count": 441,
    "plot": "Snow White, a beautiful girl, is despised by a wicked queen who tries to destroy her. With the aid of dwarves in the woods, Snow White overcomes the queen.Snow White, a beautiful girl, is despised by a wicked queen who tries to destroy her. With the aid of dwarves in the woods, Snow White overcomes the queen.Snow White, a beautiful girl.",
    "directors": "J. Searle Dawley|",
    "writers": "Winthrop Ames|Jacob Grimm|Wilhelm Grimm|",
    "stars": "Dorothy Cumming|Creighton Hale|Lionel Braham",
    "genres": "Fantasy|Romance"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0003471/?ref_=sr_t_4",
    "title": "Traffic in Souls",
    "poster": "https://m.media-amazon.com/images/M/MV5BYzk0YWQzMGYtYTM5MC00NjM2LWE5YzYtMjgyNDVhZDg1N2YzXkEyXkFqcGdeQXVyMzE0MjY5ODA@._V1_QL75_UY281_CR1,0,190,281_.jpg",
    "release_year": 1913,
    "length_in_min": 88,
    "imdb_rating": 6,
    "rating_count": 731,
    "plot": "With aid from her police-officer sweetheart, a woman endeavors to uncover the prostitution ring that has kidnapped her sister and the philanthropist who secretly runs it.With aid from her police-officer sweetheart, a woman endeavors to uncover the prostitution ring that has kidnapped her sister and the philanthropist who secretly runs it.With aid from her police-officer sweetheart.",
    "directors": "George Loane Tucker|",
    "writers": "Walter MacNamara|George Loane Tucker|",
    "stars": "Jane Gail|Ethel Grandin|William H. Turner",
    "genres": "Crime|Drama"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0003167/?ref_=sr_t_22",
    "title": "Home, Sweet Home",
    "poster": "https://m.media-amazon.com/images/M/MV5BOTZjNzg2MjgtODJkNy00NWM5LTg2MTAtZGVmZTRiOGEyODJhXkEyXkFqcGdeQXVyMjUxODE0MDY@._V1_QL75_UX190_CR0,3,190,281_.jpg",
    "release_year": 1914,
    "length_in_min": 55,
    "imdb_rating": 5.7,
    "rating_count": 283,
    "plot": "John Howard Payne at his most miserable point in life, writes a song which becomes popular and inspires other people at some point in their lives.John Howard Payne at his most miserable point in life, writes a song which becomes popular and inspires other people at some point in their lives.John Howard Payne at his most miserable point in life, writes a song which becomes popular and inspires other people at some point in their lives.",
    "directors": "D.W. Griffith|",
    "writers": "D.W. Griffith|H.E. Aitken|",
    "stars": "Henry B. Walthall|Josephine Crowell|Lillian Gish",
    "genres": "Drama"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0003772/?ref_=sr_t_21",
    "title": "Cinderella",
    "poster": "https://m.media-amazon.com/images/M/MV5BNDRhMGQ1NWMtNmZkNS00MGYxLTg0ZWUtMGRlYmZiMzQ3YTc1XkEyXkFqcGdeQXVyNDY1NzU5NjY@._V1_QL75_UY281_CR1,0,190,281_.jpg",
    "release_year": 1914,
    "length_in_min": 52,
    "imdb_rating": 6,
    "rating_count": 1100,
    "plot": "Though mistreated by her cruel stepmother and stepsisters, Cinderella is able to attend the royal ball through the help of a fairy godmother.Though mistreated by her cruel stepmother and stepsisters, Cinderella is able to attend the royal ball through the help of a fairy godmother.Though mistreated by her cruel stepmother and stepsisters, Cinderella is able to attend the royal ball through the help of a fairy godmother.",
    "directors": "James Kirkwood",
    "writers": "Charles Perrault|",
    "stars": "Mary Pickford|Owen Moore|Isabel Vernon",
    "genres": "Fantasy|Drama"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0004134/?ref_=sr_t_6",
    "title": "Hypocrites",
    "poster": "https://m.media-amazon.com/images/M/MV5BMjA5NTYzNDQ4NV5BMl5BanBnXkFtZTgwMzA5NzgwMzE@._V1_QL75_UY281_CR26,0,190,281_.jpg",
    "release_year": 1915,
    "length_in_min": 54,
    "imdb_rating": 6.5,
    "rating_count": 711,
    "plot": "The parallel stories of a modern preacher and a medieval monk, Gabriel the Ascetic, who is killed by an ignorant mob for making a nude statue representing Truth, which is also represented by... Read allThe parallel stories of a modern preacher and a medieval monk, Gabriel the Ascetic, who is killed by an ignorant mob for making a nude statue representing Truth, which is also represented by a ghostly naked girl who flits throughout the film.The parallel stories.",
    "directors": "Lois Weber",
    "writers": "Lois Weber|",
    "stars": "Courtenay Foote|Myrtle Stedman|Herbert Standing",
    "genres": "Drama|Fantasy"
  },
  {
    "movie_url": "https://www.imdb.com/title/tt0004873/?ref_=sr_t_3",
    "title": "Alice in Wonderland",
    "poster": "https://m.media-amazon.com/images/M/MV5BYjJhYzZlODYtOWE1My00ZmQ2LWJmOGYtOWFhNTAwMTgyODc4XkEyXkFqcGdeQXVyNTcwNjUwNzk@._V1_QL75_UY281_CR2,0,190,281_.jpg",
    "release_year": 1915,
    "length_in_min": 52,
    "imdb_rating": 6.1,
    "rating_count": 722,
    "plot": "Alice goes with her sister to a picnic and then she falls asleep and starts dreaming about a wonderland full of talking animals and walking playing cards.Alice goes with her sister to a picnic and then she falls asleep and starts dreaming about a wonderland full of talking animals and walking playing cards.Alice goes with her sister to a picnic and then she falls asleep and starts dreaming about a wonderland full of talking animals and walking playing cards.",
    "directors": "W.W. Young|",
    "writers": "Lewis Carroll|W.W. Young|DeWitt C. Wheeler|",
    "stars": "Viola Savoy|Herbert Rice|Elmo Lincoln",
    "genres": "Adventure|Family|Fantasy"
  }
  
];